CREATE TABLE TestTable (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numeric_column   NUMERIC(10, 2),
    string_column    VARCHAR(30),
    char_column      CHAR(10),
    date_column      DATE,
    timestamp_column TIMESTAMP,
    boolean_column   BOOLEAN,
    real_column      REAL,
    double_column    DOUBLE PRECISION,
    clob_column      TEXT
);

CREATE TABLE Member (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MemberId   NUMERIC(10),
    MemberName VARCHAR(30)
);
